### PR TITLE
Android and IOS share popup now opens properly

### PR DESCRIPTION
**Pull request by Mr-KayJayDee**
I did not try on IOS because i don't have one but it should open

Only thing left is to add the image to the files array as file:// urls so maybe we need to store them in the app cache somehow

### CODE REVIEW

**Comment by florian-lefebvre** [comment]
That's why I didn't use this plugin, because we have no way to persist the file client side. I really don't know what we can do about it. Or maybe with the file storage api on mobile?

**Comment by Mr-KayJayDee** [comment]
I understand but when I debugged I found out that navigator.share did not exists and explained why the popup did not open. Now it opens. 

As for the file maybe we can store the file on the user phone then provide the link of the file. But that means we need to request storage permissions

**Comment by Androz2091** [comment]
asking for storage permissions is not great for that purposes tbh 🤔 
we indeed need to figure out how to create a temporary file using some cache

**Comment by Mr-KayJayDee** [comment]
It's not yes. But I think that for Android the cache folder which is Android/data/app.dumpus.app is read/writable without permissions

**Comment by Mr-KayJayDee** [comment]
I might have found something, the only issue is after saving the image i cannot get the correct final uri, the in the error is returned by the file but apparently it's wrong 🤔 

image

**Comment by Mr-KayJayDee** [comment]
This will also need some IOS testing and the web sharing is still not working

**Comment by Androz2091** [comment]
Capture d’écran 2023-07-24 à 09 40 45
it does not work on iOS

it works on iOS with the `main` branch though 🤔

**Comment by Androz2091** [comment]
IMG_84EED311DA80-1

**Comment by florian-lefebvre** [comment]
Thank you! I am going to merge it to another branch so that I can work on it 👍

**Pull request merged**
