### PR TITLE
Add correct play store badge

### PR DESCRIPTION
**Pull request by Mr-KayJayDee**
Adding a badge that follows google play store guidelines

https://play.google.com/intl/en_us/badges/

Need to do it with the App Store too : https://tools.applemediaservices.com/app-store/

Enter the app name there (once it's public)

### CODE REVIEW

**Review by florian-lefebvre — COMMENTED** [review]
Is there a way to get rid of the white background surrounding the badge? Won't look good in dark mode

**Comment by Mr-KayJayDee** [comment]
Go to the first link and scroll down to Badge generator to see what you can do !

Paste this link inside it : https://play.google.com/store/apps/details?id=app.dumpus.app

**Comment by Androz2091** [comment]
we have to figure out a way so the new Google Play and new Apple Store badges are aligned and at the same width.

@Mr-KayJayDee can you add the new App Store embed (the official one) with a linking pointing to app.dumpus.app? (even if the app does not exist yet that's fine)

**Comment by Mr-KayJayDee** [comment]
Yes, we can play with `height` and `width`.

As for the app store badge I can't. The links are not related to the app package name but an id. If you have the link maybe the TestFlight one that'll be great.

Otherwise I can use a random app link for now

**Comment by Androz2091** [comment]
Yes, a random link is fine tbh
pointing to Discord for instance

**Comment by Androz2091** [comment]
Capture d’écran 2023-07-28 à 12 47 19
honestly, we can't have this in the repo... it's not clean enough 😕 
badges are way better (as it's the new UI), but it's not centered

**Comment by Mr-KayJayDee** [comment]
I tried my best to center and align them but the issue is that the google play badge has a margin and the apple does not have it. Also i tried to play with the height and it looked ok on my end but apparently it's not on yours 😓

**Comment by Mr-KayJayDee** [comment]
My bad, i accidentely deleted the branch 😅

**Comment by Mr-KayJayDee** [comment]
@Androz2091 what should we do with this ? close or resolve ? you already updated the code without merging this pr 🤔

**Comment by florian-lefebvre** [comment]
My bad, I wanted to go fast and completely forgot about this PR 😬I guess we should close it. Waiting for @Androz2091's opinion

**Review by Androz2091 — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
