### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by Justman100** [comment]
@florian-lefebvre

**Comment by Justman100** [comment]
@florian-lefebvre

**Comment by Androz2091** [comment]
Thank you for contributing! I do not see any point in these changes though. 
Cheers, Simon

**Comment by Justman100** [comment]
> Thank you for contributing! I do not see any point in these changes though. Cheers, Simon

Are you kidding me? If it didn't make sense, this PR wouldn't even exist!

> More than 10 top DMs/servers/channels
is wrong because it's a yes-no formulation, but the values contain numbers instead of yes or no! Ergo, it's wrong! You dirt idiots should think before you act! The same applies to closing issues and PRs! Always wait for an answer from the issue/PR creator before proceeding!

Then handle your shit yourself! Dirt idiot! That's how you lose your users! But I'm sure you don't care about that! They're just people with feelings!

**Comment by Androz2091** [comment]
Hey, thank you for your comment and I am sincerely sorry about your frustration in the way I handled this PR. The little icons :heavy_check_mark: and :x: means indeed yes and no, and asking whether you can or not view more than 10 is a yes/no question. With some precisions in parenthesis about the specific number. 
What do you think about this explanation?

**Comment by Androz2091** [comment]
Also, please stay respectful if you want me to "care" about you.

**Comment by Justman100** [comment]
> Hey, thank you for your comment and I am sincerely sorry about your frustration in the way I handled this PR. The little icons ✔️ and ❌ means indeed yes and no, and asking whether you can or not view more than 10 is a yes/no question. With some precisions in parenthesis about the specific number. What do you think about this explanation?

The part in the brackets still makes no sense! Also, one can create more commits! But yes, just destroy the work of others! There's nothing to it

**Comment by Justman100** [comment]
> Also, please stay respectful if you want me to "care" about you.

Says the right person who simply destroys the work of others

**Pull request closed without merging**
